apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: demo-repl
  namespace: gum-labs
  labels:
    srv: demo-repl
spec:
  replicas: 3
  selector:
    matchLabels:
      srv: demo-repl
  template:
    metadata:
      labels:
        srv: demo-repl
        domain: seneca-base
    spec:
      containers:
      - name: demo-repl
        image: tegamckinney/demo-repl:7
        ports:
          - containerPort: 39000
          - containerPort: 10000
      serviceAccountName: seneca-mesh-pod-reads-ns
